# Generated by Django 5.2 on 2025-12-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwebapp', '0002_importantdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_students', models.IntegerField()),
                ('students_placed', models.IntegerField()),
                ('highest_package', models.CharField(max_length=50)),
                ('average_package', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='RecruitingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='Optional: Company logo URL')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name_plural': 'Recruiting Companies',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('package', models.CharField(help_text='e.g., 12 LPA', max_length=50)),
                ('year', models.IntegerField(help_text='Placement year')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwebapp.department')),
            ],
            options={
                'ordering': ['-year', 'company_name'],
            },
        ),
    ]
