# Generated by Django 5.2 on 2025-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwebapp', '0005_event_photo_faculty_photo_news_file_news_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_photo',
            field=models.ImageField(blank=True, null=True, upload_to='department_heads/'),
        ),
    ]
