# Generated by Django 5.2.5 on 2025-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshoppingapp', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
